name = "ElectricGrid"
uuid = "d6749236-802c-4af3-9b09-2fcebf7269d7"
version = "1.0.0"

[deps]
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"
ReinforcementLearningCore = "de1b191a-4ae0-4afa-a27b-92d07f46b2d6"


[compat]
ReinforcementLearning = "0.10.2"
ReinforcementLearningCore = "0.8.13"

